[tool.ruff]
line-length = 88
target-version = "py310"
unfixable = []

select = [
    "F",
    "E",
    "W",
    "I",
    "YTT",
    "B",
    "Q",
    "T10",
    "INT",
    "PLC",
    "PLE",
    "PLW",
    "PIE",
    "PYI",
    "ISC",
    "TCH",
    "C4",
    "PGH",
    "RUF",
    "S102",
    "NPY002",
    "PERF",
]

ignore = [
    "E203",
    "E402",
    "E731",
    "B006",
    "B007",
    "B008",
    "B009",
    "B010",
    "B011",
    "B015",
    "B019",
    "B020",
    "B023",
    "B905",
    "PLR0913",
    "PLR0911",
    "PLR0912",
    "PLR0915",
    "PLW2901",
    "PLW0603",
    "PYI021",
    "PGH001",
    "PLC1901",
    "PERF102",
    "PERF203",
]

exclude = [
    ".git",
    ".venv",
    "build",
    "dist",
    "docs",
    "logs",
]

[tool.mypy]
ignore_missing_imports = true

exclude = [
    ".git",
    ".venv",
    "build",
    "dist",
    "docs",
    "logs",
    "setup.py",
]
