name: Code check

on:
  push:
    branches: [master]

jobs:
  code-check:
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          python -m pip install pre-commit mypy types-tqdm pandas-stubs pytest pytest-mock
          pre-commit install

      - name: Run pre-commit
        run: |
          if [[ "${{ matrix.python-version }}" == "3.8" ||
                "${{ matrix.python-version }}" == "3.9" ]]; then
            SKIP=mypy pre-commit run --all-files --verbose
          else
            pre-commit run --all-files --verbose
          fi

      - name: Run unit tests
        run: |
          pytest ml3m
